language: node_js
node_js:
- node
before_script:
- npm install grunt-cli -g
- export CHROME_BIN=chromium-browser
- export DISPLAY=:99.0
- sh -e /etc/init.d/xvfb start
- node server &
- sleep 3
deploy:
  provider: npm
  email: npm@vokal.io
  api_key: $NPM_API_KEY
  on:
    tags: true
    repo: vokal/angular-datetime
